# Setup
title:               'Andy Fries'
tagline:             'My thoughts, loosely collected'
description:         ''
url:                 https://andyfries.com
baseurl:             ''
paginate:            5
permalink:           /:title/
excerpt_separator:   '<!--more-->'

# About/contact
author:
  name:              Andy Fries
  email:             contact@andyfries.com

# Gems
plugins:
  - jekyll-paginate

# Markdown
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Custom vars
google_analytics_id: G-TWCTGMEFFE

